# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

# obj-y += focaltech_test_config_ft8716.o
# obj-y += focaltech_test_ft8716.o
# obj-y += focaltech_test_config_ft8607.o	
# obj-y += focaltech_test_ft8607.o
 obj-y += focaltech_test_config_ft5x46.o	
 obj-y += focaltech_test_ft5x46.o

obj-y += focaltech_test_supported_ic.o
